jtype: StableDiffusionGenerator
with:
  batch_size: 4
  height: 512
  max_n_subprompts: 8
  max_resolution: 589824 # 768x768
  n_iter: 1
  use_half: True
  weights_path: ../stable-diffusion/models/ldm/stable-diffusion-v1/model.ckpt
  width: 512
metas:
  py_modules:
    - executor.py